# Generated by Django 2.0.4 on 2018-11-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
